package domain;

public enum SystemMessageType {
    LOGIN_REQUEST,

    LOGIN_OK,
    NEW_CONVERSATION_REQUEST,
    NEW_CONVERSATION_OK,
    NEW_CONVERSATION_FAIL,
    CONVERSATION_CONNECT_REQUEST,
    CONVERSATION_CONNECT_OK,
    CONVERSATION_CONNECT_FAIL,
    ADD_MEMBER

}

