package domain;

public enum SystemMessageType {
    LOGIN_REQUEST,

    LOGIN_OK,
    NEW_CONVERSATION_REQUEST,
    PRIVATE_CONVERSATION_REQUEST,
    CONVERSATION_CONNECT_REQUEST,
    CONVERSATION_CONNECT_OK,
    ADD_MEMBER

}

